[package]
name = "liquid-penguin"
version = "0.1.0"
edition = "2021"


[dependencies]
env_logger = "0.9.0"
serde = { version = "1.0", optional = true }
bitcoin = "0.28.1"
secp256k1-sys = "=0.4.1"
elementsd = {version = "0.5.0", features=["0_21_0","bitcoind_22_0"]}